matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
dist: trusty
sudo: required
language:
  - cpp
#before_script:
#  - sudo pip install pexpect
script:
  - export CC=gcc-6
  - export CXX=g++-6
  - make test_all
after_success:
  - if [ "$CXX" == "g++-6" ]; then
        cd test_results;
        bash <(curl -s https://codecov.io/bash);
    fi;