os: linux
dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
script:
  - sudo apt-get --only-upgrade gcc
  - make
  - pip install --user cpp-coveralls
after_success:
  - if [ "$CXX" == "g++" ]; then
        coveralls --exclude tests --gcov-options '\-lp \--relative-only';
    fi;